- config.ts
> content: 1.1.3

- config.ts
> content: 1.1.6

- app_data/sheets/template/feedback.json
- config.ts
> content: 1.1.23

- config.ts
- reports/summary.json
- reports/summary.md
Report generated on the PR branch https://github.com/IDEMSInternational/open-app-builder/pull/2450
> content: 1.1.41 - update report

- app_data/sheets/data_list/characters.json
- app_data/sheets/template/article.json
- app_data/sheets/template/relax.json
- config.ts
- reports/summary.json
- reports/summary.md
> content: 1.1.44

- config.ts
@FaithDaka please inspect the preview link below to see the effects that the theme changes have on the `plh_kids_kw` deployment
> Update theme to plh_kids_kw

- app_data/sheets/contents.json
- app_data/sheets/generator/check_in_article_generator.json
- app_data/sheets/template/article.json
- app_data/sheets/template/generated/article_childdevelopment_check_in_3.json
- app_data/sheets/template/generated/article_consequences_check_in_13.json
- app_data/sheets/template/generated/article_feelings_check_in_7.json
- app_data/sheets/template/generated/article_instructions_check_in_8.json
- app_data/sheets/template/generated/article_oneononetime_check_in_4.json
- app_data/sheets/template/generated/article_praise_check_in_6.json
- app_data/sheets/template/generated/article_problemsolving_check_in_16.json
- app_data/sheets/template/generated/article_rulesroutines_check_in_12.json
- app_data/sheets/template/generated/article_selfcare_check_in_1.json
- app_data/sheets/template/module.json
- app_data/sheets/template/question.json
- config.ts
- reports/summary.json
- reports/summary.md
make check in module specific following change in kids tz
> content: 1.1.49

- app_data/sheets/contents.json
- app_data/sheets/data_list/generated/consequences_article_tasks.json
- app_data/sheets/data_list/generated/module_tasks.json
- app_data/sheets/data_list/modules/consequences_articles.json
- app_data/sheets/data_pipe/prep_modules.json
- app_data/sheets/template/home_screen.json
- app_data/sheets/template/module.json
- app_data/sheets/template/module_card.json
- config.ts
- fix completion and in-progress tags on module path homescreen
- fix locking on module list homescreen
> content: 1.1.53

- app_data/sheets/template/home_screen.json
- config.ts
- Sticky header (see https://github.com/IDEMSInternational/open-app-builder/pull/2564#pullrequestreview-2470325918) - awaiting bug fix on code PR
- Add default theme for debugging purposes
> content: 1.1.56

- config.ts
Populate android and ios config
> content: 1.1.72

- config.ts
Now shows Arabic translation of Dayem App
> Update text that appears in browser tab and side menu

- app_data/sheets/contents.json
- app_data/sheets/global/deployment_global_kw.json
- app_data/sheets/template/app_menu.json
- app_data/sheets/template/countdown_days.json
- app_data/sheets/template/enter_dev_mode.json
- app_data/sheets/template/hp_review.json
- app_data/sheets/template/module.json
- app_data/sheets/template/module_landing.json
- app_data/sheets/template/question.json
- config.ts
- update radio group style in modules and hp review 
known issue: https://github.com/IDEMSInternational/open-app-builder/issues/2641
1. sizing is sometimes a bit funky
- update testing pw to `DayemTest`
- update enter dev mode template so that no double button click is needed
- add countdown days template
- add hp review button with 7 day delay 
running off PR branch https://github.com/IDEMSInternational/open-app-builder/pull/2562
known issues: https://github.com/IDEMSInternational/open-app-builder/pull/2562#pullrequestreview-2518678746
1.  when module is not yet completed, currently shows unlocked. This should instead be locked without countdown bar.
2. display is not horizontally aligned with progress wheel
Following merge of this PR (i.e. on version 1.1.75), the delayed unlocking of hp …
> content: 1.1.75

- app_data/sheets/template/activity_library.json
- config.ts
Remove description from activity library + reduce margin so that more content fits on screen.
> content: 1.2.1

- app_data/sheets/template/activity.json
- config.ts
removed sticky top as close still not appearing on i-phones
> content: 1.2.4

- app_data/sheets/template/activity.json
- config.ts
- reports/summary.json
- reports/summary.md
Testing web preview on i-phones
> content: 1.2.5

- app_data/sheets/template/activity.json
- config.ts
- reports/summary.json
- reports/summary.md
moved close button down to fix i-phone issue
> content: 1.2.6

- app_data/sheets/template/activity_library.json
- config.ts
Sort activities to show unlocked first
> content: 1.2.11

- app_data/sheets/contents.json
- app_data/sheets/data_list/generated/module_tasks.json
- app_data/sheets/data_list/generated/oneononetime_article_tasks.json
- app_data/sheets/data_list/language_reversed.json
- app_data/sheets/data_list/modules/modules.json
- app_data/sheets/data_list/modules/oneononetime_articles.json
- app_data/sheets/template/language_select.json
- app_data/sheets/template/module_card.json
- app_data/sheets/template/settings_margins.json
- app_data/translations/kw_ar/strings.json
- app_data/translations_source/translated_strings/translated.kw_ar.json
- config.ts
- reports/summary.json
- reports/summary.md
- In `language_select` template, English button now always appears left and Arabic button always right
- Update Child Development module title + translation
> content: 1.2.13

- app_data/sheets/template/app_menu.json
- app_data/sheets/template/article.json
- app_data/sheets/template/header.json
- app_data/sheets/template/language_select.json
- app_data/sheets/template/module_landing.json
- config.ts
- reports/summary.json
- reports/summary.md
- add button to \user in developer menu
- improve spacing around module header
- centre text on module landing buttons
> content: 1.2.14

- .github/workflows/android-release.yml
- .github/workflows/content-sync.yml
- .github/workflows/deploy-firebase.yml
- .github/workflows/deploy-pr-preview.yml
- .github/workflows/firebase-release.yml
Reverts ParentingForLifelongHealth/plh-kids-app-kw-content#139
> Revert "fix: configure github actions to inherit secrets"

- app_data/sheets/template/login.json
- config.ts
- reports/summary.json
- reports/summary.md
> content: 1.2.18

- app_data/sheets/template/module_list.json
- app_data/sheets/template/module_list_item.json
- app_data/sheets/template/module_path.json
- app_data/sheets/template/question.json
- config.ts
- reports/summary.json
- reports/summary.md
> content: 1.2.27

- app_data/sheets/contents.json
- app_data/sheets/template/question_archived.json
- config.ts
> content: 1.2.29

- app_data/sheets/template/relax_activities.json
- app_data/sheets/template/relax_card.json
- app_data/sheets/template/settings.json
- app_data/sheets/template/settings_login.json
- app_data/sheets/template/user_data.json
- config.ts
- reports/summary.json
- reports/summary.md
Add force reload so that "Sign in" / "Sign out" button text in Settings updates immediately
https://github.com/user-attachments/assets/b1fcd1a4-c823-4bda-82b4-99d4f1b64344
Closes #53
> content: 1.2.35

- app_data/sheets/global/deployment_global_kw.json
- app_data/sheets/template/user_data.json
- config.ts
- reports/summary.json
- reports/summary.md
- Fix homepage highlighting bug
> content: 1.3.0

- app_data/sheets/template/login.json
- config.ts
- reports/summary.json
- reports/summary.md
Adds Apple sign in button on login splash screen
> content: 1.3.4

- app_data/assets/contents.json
- app_data/assets/images/icons/expand_circle_left_blue.svg
- app_data/assets/images/icons/expand_circle_right_blue.svg
- app_data/sheets/contents.json
- app_data/sheets/global/deployment_global_kw.json
- app_data/sheets/template/activity.json
- app_data/sheets/template/activity_library.json
- app_data/sheets/template/home_screen.json
- app_data/sheets/template/home_screen_header.json
- app_data/sheets/template/unlock_play.json
- config.ts
- reports/summary.json
- reports/summary.md
> content: 1.4.1

- app_data/sheets/contents.json
- app_data/sheets/data_list/generated/oneononetime_article_tasks.json
- app_data/sheets/data_list/generated/rulesroutines_article_tasks.json
- app_data/sheets/data_list/modules/oneononetime_articles.json
- app_data/sheets/data_list/modules/rulesroutines_articles.json
- app_data/sheets/generator/oneononetime_article_gen.json
- app_data/sheets/template/article.json
- app_data/sheets/template/check_field_value.json
- app_data/sheets/template/generated/article_oneononetime_tips_2.json
- app_data/sheets/template/generated/article_oneononetime_tips_3.json
- config.ts
- reports/summary.json
- reports/summary.md
> content: 1.4.6
